<?php

/**
 * @file
 * Contains hook implementations for drupalcampfr_newsletter module.
 */

define('DRUPALCAMPFR_NEWSLETTER_DEFAULT_ACCOUNT_HASH', 'eb7ebedd32b3b2fc0ac192ee9');
define('DRUPALCAMPFR_NEWSLETTER_DEFAULT_MAILING_LIST_HASH', '26bff72b56');
define('DRUPALCAMPFR_NEWSLETTER_DEFAULT_ANTI_SPAM_TOKEN', 'b_eb7ebedd32b3b2fc0ac192ee9_450c6dc6d6');

/**
 * Implements hook_theme().
 */
function drupalcampfr_newsletter_theme($existing, $type, $theme, $path) {
  return [
    'drupalcampfr_newsletter_subscription_block' => [
      'variables' => [
        'account_hash' => DRUPALCAMPFR_NEWSLETTER_DEFAULT_ACCOUNT_HASH,
        'mailing_list_hash' => DRUPALCAMPFR_NEWSLETTER_DEFAULT_MAILING_LIST_HASH,
        'anti_spam_token' => DRUPALCAMPFR_NEWSLETTER_DEFAULT_ANTI_SPAM_TOKEN,
      ],
    ],
  ];
}
