<?php

/**
 * @file
 * Contains hook implementations for drupalcampfr_ticket module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Remove the submit button on the cart.
 */
function drupalcampfr_ticket_form_views_form_commerce_cart_form_default_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['actions']['submit'])) {
    unset($form['actions']['submit']);
  }
}
