# Schema for the configuration files of the Drupalcampfr social module.

drupalcampfr_social.twitter:
  type: config_object
  label: 'Settings for Twitter connection'
  mapping:
    consumer_key:
      type: string
      label: 'Consumer key'
    consumer_secret:
      type: string
      label: 'Consumer secret'
    access_token:
      type: string
      label: 'Access token'
    access_token_secret:
      type: string
      label: 'Access token secret'
