<?php

/**
 * @file
 * Contains hook implementations for drupalcampfr_user module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_menu_links_discovered_alter().
 *
 * Disable default links provided by the user module.
 */
function drupalcampfr_user_menu_links_discovered_alter(&$links) {
  $user_links = array(
    'user.logout',
    'user.page',
  );

  foreach ($user_links as $user_link) {
    if (isset($links[$user_link])) {
      $links[$user_link]['enabled'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Hide field on user form.
 */
function drupalcampfr_user_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $current_user = \Drupal::currentUser();
  if (!$current_user->hasPermission('administer users') && isset($form['field_user_is_attendee'])) {
    $form['field_user_is_attendee']['#access'] = FALSE;
  }
}
