<?php

function dcp2019_theme() {
  $theme = [];
  $theme['hp_slider_block'] = [
    'template' => 'hp-slider-block',
    'variables' => [
    ],
  ];
  $theme['hp_place'] = [
    'template' => 'hp-place',
    'variables' => [
    ],
  ];
  $theme['hp_inscription'] = [
    'template' => 'hp-inscription',
    'variables' => [
    ],
  ];
  return $theme;
}


function dcp2019_preprocess(&$variables, $hook) {
  $variables['pathtotheme'] = base_path() . drupal_get_path('theme', \Drupal::theme()->getActiveTheme()->getName());
}
