<?php

/**
 * @file
 * Contains hook implementations for drupalcampfr_sponsor module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function drupalcampfr_sponsor_form_webform_submission_sponsor_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Remove options where sponsor level is disabled.
  if (isset($form['elements']['level']) && isset($form['elements']['level']['#options'])) {
    /** @var Drupal\Core\Entity\Query\QueryFactory $entity_query */
    $entity_query = \Drupal::getContainer()->get('entity.query');

    $disabled_sponsor_levels_ids = $entity_query->get('taxonomy_term', 'AND')
      ->condition('vid', 'sponsor_levels')
      ->condition('field_sponsor_level_status', FALSE)
      ->execute();

    foreach ($disabled_sponsor_levels_ids as $sponsor_level_tid) {
      unset($form['elements']['level']['#options'][$sponsor_level_tid]);
    }
  }
}
