<?php

/**
 * @file
 * Contains hook implementations for drupalcampfr_social module.
 */

/**
 * Implements hook_theme().
 */
function drupalcampfr_social_theme($existing, $type, $theme, $path) {
  return array(
    'drupalcampfr_social_twitter_statuses' => array(
      'variables' => array(
        'statuses' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_drupalcampfr_social_twitter_statuses().
 */
function drupalcampfr_social_preprocess_drupalcampfr_social_twitter_statuses(&$variables) {
  /** @var Drupal\Core\Datetime\DateFormatterInterface $date_formatter */
  $date_formatter = \Drupal::service('date.formatter');

  foreach ($variables['statuses'] as $key => $status) {
    // Format creation date.
    $created_at = \DateTime::createFromFormat('D M d H:i:s O Y', $variables['statuses'][$key]->created_at);
    $variables['statuses'][$key]->created_at = $date_formatter->format($created_at->getTimestamp(), 'long');

    // Format tweet text.
    $variables['statuses'][$key]->text = check_markup($variables['statuses'][$key]->text, 'restricted_html');
  }
}
